export const strengths = [
  {
    main: "Diseño Industrial",
    baseVelocity: -3,
    categories: [
      "Design thinking",
      "Digital manufacturing",
      "Phisical computing",
      "Human computer Interaction",
      "User experience",
      "Electronics",
      "Musical instruments",
      "3D modeling",
      "CAD",
      "CAM",
      "Fusion360",
      "Blender",
      "3D priners",
      "CNC Router",
      "Duet3D RepRap",
      "GRLB",
      "GCode",
      "Arduino",
    ],
  },
  {
    main: "UX / UI",
    baseVelocity: -6,
    categories: [
      "Design thinking",
      "User experience",
      "Grahpic Design",
      "Digital mockups",
      "wire Frames",
      "Figma",
      "Gimp",
      "Inkscape",
      "Invision",
    ],
  },
  {
    main: "Desarrollador de Software",
    baseVelocity: -4,
    categories: [
      "Fronted Develop",
      "Mobile App Develop",
      "Game developer",
      "ReactJS",
      "React Native",
      "NodeJS",
      "Javascript",
      "css",
      "Html",
      "C",
      "C++",
      "Arduino",
      "Gcode",
      "OpenframeWorks",
      "processing",
      "Unity3D",
      "Godot",
      "Construct3",
    ],
  },
  {
    main: "Docencia",
    baseVelocity: -4,
    categories: [
      "Design thinking",
      "User Experince",
      "Phisical computing",
      "Human computer Interaction",
      "Game design",
      "Game develop",
      "Electronics",
      "Digital manofacturing",
      "Musical instruments",
      "Arduino",
      "3d printer",
      "CNC router",
    ],
  },
];
