export const strengths = [
  {
    main: "Diseñador",
    baseVelocity: -4.5,
    categories: [
      "Design thinking",
      "Digital manufacturing",
      "Phisical computing",
      "Human computer Interaction",
      "Grahpic Design",
      "UX / UI",
      "Electronics",
      "Musical instruments",
      "3D modeling",
      "CAD",
      "CAM",
      "Fusion360",
      "FreeCad",
      "Blender",
      "Figma",
      "Gimp",
      "Inkscape",
      "Invision",
      "Midjouney",
    ],
  },
  {
    main: "Desarrollador de Software",
    baseVelocity: -4,
    categories: [
      "Fronted",
      "Backend",
      "Mobile App Develop",
      "Game developer",
      "Embedded system",
      "ReactJs",
      "AngularJs",
      "NextJs",
      "Server side Rendering",
      "NodeJs",
      "Postgress",
      "mySQL",
      "php",
      "Javascript",
      "css",
      "Html",
      "C",
      "C++",
      "Craft CMS",
      "OpenframeWorks",
      "processing",
      "Unity3D",
      "Unreal Engine",
      "Godot",
      "Construct3",
      "RaspberryPi",
    ],
  },
  {
    main: "Fabricación Digital",
    baseVelocity: -5,
    categories: [
      "3D priners",
      "CNC Router",
      "Duet3D RepRap firmware",
      "Photogrametry",
      "Electronics",
      "sensors",
      "Actuators",
      "GRLB",
      "Gcode",
      "Ectlcam",
      "Prusa Slicer",
      "simplify3D",
      "workbee CNC",
      "Cartesian kinematic",
      "Delta kinematic",
    ],
  },
  {
    main: "Docencia",
    baseVelocity: -5,
    categories: [
      "Design thinking",
      "User Experince",
      "Phisical computing",
      "Human computer Interaction",
      "UX / UI",
      "Game design",
      "Game develop",
      "Electronics",
      "Digital manofacturing",
      "Musical instruments",
      "Arduino",
      "3d printer",
      "CNC router",
    ],
  },
];
